// AUTH types
export const AUTH_USER = "AUTH_USER";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_FAIL = "AUTH_FAIL";

// CART types
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const MOVE_TO_WISHLIST = "MOVE_TO_WISHLIST";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const PLUS_COUNTER_PRODUCT = "PLUS_COUNTER_PRODUCT";
export const MINUS_COUNTER_PRODUCT = "MINUS_COUNTER_PRODUCT";